// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYRBnfRjsBWOy5PqUzsk6vdG3ulQ9_cWc',
    appId: '1:670590787220:web:2872332573b7ee2150de81',
    messagingSenderId: '670590787220',
    projectId: 'flutterproject-c478e',
    authDomain: 'flutterproject-c478e.firebaseapp.com',
    storageBucket: 'flutterproject-c478e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC56XWYJpubYlyrHD1k6xs-gbeakgbEhAA',
    appId: '1:670590787220:android:9ae5c2a7ead2602a50de81',
    messagingSenderId: '670590787220',
    projectId: 'flutterproject-c478e',
    storageBucket: 'flutterproject-c478e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy06WVrb8Lo92GlBnOYATgeAedJlWOBlg',
    appId: '1:670590787220:ios:a6e5a0b505cfe7a450de81',
    messagingSenderId: '670590787220',
    projectId: 'flutterproject-c478e',
    storageBucket: 'flutterproject-c478e.appspot.com',
    iosClientId: '670590787220-3pr8lr134utrv1mo568fcq23qp7gjark.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPengajuanCuti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy06WVrb8Lo92GlBnOYATgeAedJlWOBlg',
    appId: '1:670590787220:ios:a6e5a0b505cfe7a450de81',
    messagingSenderId: '670590787220',
    projectId: 'flutterproject-c478e',
    storageBucket: 'flutterproject-c478e.appspot.com',
    iosClientId: '670590787220-3pr8lr134utrv1mo568fcq23qp7gjark.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPengajuanCuti',
  );
}
